// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sfxifyrtdyndjfiszoyk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNmeGlmeXJ0ZHluZGpmaXN6b3lrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3MzUyNTMsImV4cCI6MjA3MDMxMTI1M30.llshHwedzm2BtR4HdEVZcjL68-M-ftxV2xOV5Tm0GvU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});